### ISSUE TITLE
potential package: maths

### ISSUE THREAD

**Issue by aslilac** [gleam-community/META#1]
Nicklas had mentioned an interest in creating a mathematics focused library based on some prior work in <https://github.com/NicklasXYZ/gleam_stats>

**Comment by NicklasXYZ** [comment]
Yeah, I hope to get started tomorrow. I just had to get over my PhD defense 😃

**Comment by NicklasXYZ** [comment]
I imagine I will be re-organizing the math functions implemented in the `gleam_stats` package according to the functions applying to integer and floating point values, a bit like how things are organized in the stdlib with int and float functions .

**Comment by aslilac** [comment]
I'm gonna close this since we've made the maths repo public now, with it scheduled to be published soon. :)
